config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  # devise_for :users
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  root 'pages#index'

  resources :posts do
    collection do
      get 'hobby'
      get 'study'
      get 'team'
    end
  end

  namespace :private do
    resources :conversations, only: [:create] do
      member do
        post :close
        post :open
      end
    end
    resources :messages, only: %i[index create]
  end

  resources :contacts, only: %i[create update destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end

  # render the navigation header's content
  def nav_header_content_partials
    partials = []
    if params[:controller] == 'messengers'
      partials << 'layouts/navigation/header/messenger_header'
    else # controller is not messengers
      partials << 'layouts/navigation/header/toggle_button'
      partials << 'layouts/navigation/header/home_button'
      partials << 'layouts/navigation/header/dropdowns' if user_signed_in?
    end
    partials
  end

  # return a conversation header partial's path
  def conversation_header_partial_path(conversation)
    if conversation.class == Private::Conversation
      'layouts/navigation/header/dropdowns/conversations/private'
    else
      'layouts/navigation/header/dropdowns/conversations/group'
    end
  end
end

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li ><%= link_to 'Login', login_path %></li>
<li ><%= link_to 'Signup', signup_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="dropdown pc-menu">
  <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
    <span id="user-name"><%= current_user.name %></span>
    <span class="caret"></span>
  </a>

  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
  </ul>
</li>

<li class="mobile-menu">
  <%= link_to 'Edit Profile', edit_user_registration_path %>
</li>
<li class="mobile-menu">
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
</li>